package edu.hnu.citi.trainning.userclient.entity;

import java.util.Date;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbggenerated Thu Jun 22 16:42:58 CST 2023
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.name
     *
     * @mbggenerated Thu Jun 22 16:42:58 CST 2023
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.email
     *
     * @mbggenerated Thu Jun 22 16:42:58 CST 2023
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.institute
     *
     * @mbggenerated Thu Jun 22 16:42:58 CST 2023
     */
    private String institute;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.INSERT_ID
     *
     * @mbggenerated Thu Jun 22 16:42:58 CST 2023
     */
    private String insertId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.INSERT_TS
     *
     * @mbggenerated Thu Jun 22 16:42:58 CST 2023
     */
    private Date insertTs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.UPDATE_ID
     *
     * @mbggenerated Thu Jun 22 16:42:58 CST 2023
     */
    private String updateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.UPDATE_TS
     *
     * @mbggenerated Thu Jun 22 16:42:58 CST 2023
     */
    private Date updateTs;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbggenerated Thu Jun 22 16:42:58 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbggenerated Thu Jun 22 16:42:58 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.name
     *
     * @return the value of user.name
     *
     * @mbggenerated Thu Jun 22 16:42:58 CST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.name
     *
     * @param name the value for user.name
     *
     * @mbggenerated Thu Jun 22 16:42:58 CST 2023
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.email
     *
     * @return the value of user.email
     *
     * @mbggenerated Thu Jun 22 16:42:58 CST 2023
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.email
     *
     * @param email the value for user.email
     *
     * @mbggenerated Thu Jun 22 16:42:58 CST 2023
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.institute
     *
     * @return the value of user.institute
     *
     * @mbggenerated Thu Jun 22 16:42:58 CST 2023
     */
    public String getInstitute() {
        return institute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.institute
     *
     * @param institute the value for user.institute
     *
     * @mbggenerated Thu Jun 22 16:42:58 CST 2023
     */
    public void setInstitute(String institute) {
        this.institute = institute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.INSERT_ID
     *
     * @return the value of user.INSERT_ID
     *
     * @mbggenerated Thu Jun 22 16:42:58 CST 2023
     */
    public String getInsertId() {
        return insertId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.INSERT_ID
     *
     * @param insertId the value for user.INSERT_ID
     *
     * @mbggenerated Thu Jun 22 16:42:58 CST 2023
     */
    public void setInsertId(String insertId) {
        this.insertId = insertId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.INSERT_TS
     *
     * @return the value of user.INSERT_TS
     *
     * @mbggenerated Thu Jun 22 16:42:58 CST 2023
     */
    public Date getInsertTs() {
        return insertTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.INSERT_TS
     *
     * @param insertTs the value for user.INSERT_TS
     *
     * @mbggenerated Thu Jun 22 16:42:58 CST 2023
     */
    public void setInsertTs(Date insertTs) {
        this.insertTs = insertTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.UPDATE_ID
     *
     * @return the value of user.UPDATE_ID
     *
     * @mbggenerated Thu Jun 22 16:42:58 CST 2023
     */
    public String getUpdateId() {
        return updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.UPDATE_ID
     *
     * @param updateId the value for user.UPDATE_ID
     *
     * @mbggenerated Thu Jun 22 16:42:58 CST 2023
     */
    public void setUpdateId(String updateId) {
        this.updateId = updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.UPDATE_TS
     *
     * @return the value of user.UPDATE_TS
     *
     * @mbggenerated Thu Jun 22 16:42:58 CST 2023
     */
    public Date getUpdateTs() {
        return updateTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.UPDATE_TS
     *
     * @param updateTs the value for user.UPDATE_TS
     *
     * @mbggenerated Thu Jun 22 16:42:58 CST 2023
     */
    public void setUpdateTs(Date updateTs) {
        this.updateTs = updateTs;
    }
}