server:
  port: 8000

spring:
  application:
    name: hello-client  #???

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true #??????ip?????eureka?
    ip-address: 127.0.0.1 #??????ip
    instance-id: ${eureka.instance.ip-address}:${spring.application.name}:${server.port} #??web???????? id
    lease-renewal-interval-in-seconds: 30 #???eureka client?eureka server?????????
    lease-expiration-duration-in-seconds: 90 #??90??eureka server??????????????client

  client:
    service-url:
      defaultZone: http://localhost:1111/eureka  #eureka???????????????eureka??

